apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-17T16:10:58Z"
  name: webapp-config-map
  namespace: default
  resourceVersion: "1061"
  uid: 17837891-e162-42c8-b952-e929bf472900

data:
  APP_COLOR: darkblue
  APP_OTHER: disregard 
