apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
      - name: local-pvc
        mountPath: /var/www/html

  volumes:
  - name: local-pvc
    persistentVolumeClaim:
      claimName: local-pvc

---
# persistent volume claim to claim the volume defined above
# Path: pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---