apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-06-20T16:23:40Z"
  name: developer
  namespace: blue
  resourceVersion: "2789"
  uid: dc760b6a-5461-4fa6-bac2-58decd5a62ee
rules:
- apiGroups:
  - apps
  resourceNames:
  - dark-blue-app
  resources:
  - pods
  verbs:
  - get
  - watch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create 
